name: Bigquery.Almaren
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name : Check out repository code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Build and test scala version
        run: |
          PGPASSWORD="postgres" psql -c 'create database almaren;' -U postgres -h localhost 
          PGPASSWORD="postgres" psql -c "ALTER USER postgres PASSWORD 'foo' ;" -U postgres -h localhost 
          PGPASSWORD="postgres" psql -c 'create role runner;' -U postgres -h localhost
          PGPASSWORD="postgres" psql -c 'ALTER ROLE "runner" WITH  LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;' -U postgres -h localhost
          sbt ++2.12.10 test
          sbt ++2.13.9 test
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
        env:
          GCP_TOKEN: ya29.a0Aa4xrXM3a-D7x2gZhgRO9-raEAQDo-bJy9dDXXvA0e_mtE_mMteEn_bvmRgHcA4ub9ge14nw1_ubV75lf573AH3Ffke_sgY_MqIBrHLukiNe9FQJHP47FdNLrNew0kvjzAP7uYHGTXruO3yzEZdyG0GvcWkAQ8-6OlTg2IrGOZMTBY-cN66gNd2-LJz13WzQWVYq1GieSdy4wqRSP2FET5576_j0IMRhlM5oxDdL3ygxkybPvsvTCYsb767rZnSlIYZvCgaCgYKATASARMSFQEjDvL9p56iFoMs7fTNw9s_tVMI1w0269